name: Create and publish a Docker image

on:
  schedule:
    - cron: "*/3 * * * *"
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Echo!
        run: |
          echo "${{ steps.meta.outputs.tags }}"
          echo "${{ steps.meta.outpus.labels }}"
